// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotingApp_RESTAPI.DBContexts;

namespace VotingApp_RESTAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221022101319_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VotingApp_RESTAPI.Models.Candidate", b =>
                {
                    b.Property<string>("Pesel")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.HasKey("Pesel");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("VotingApp_RESTAPI.Models.Voter", b =>
                {
                    b.Property<string>("Pesel")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasVoted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pesel");

                    b.ToTable("Voters");
                });
#pragma warning restore 612, 618
        }
    }
}
